### ISSUE TITLE
Error thrown when querying records with `from: 'did-string`

### ISSUE THREAD

**Issue by dayhaysoos** [TBD54566975/web5-js#201]
### Alpha version: api@0.8.0-alpha-20230825-adebf25

I set up a basic HTML file to test querying records:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web5 API Library Demo</title>
</head>
<body>

<script async type="module">
    import {Web5} from 'https://www.unpkg.com/@web5/api@0.8.0-alpha-20230825-adebf25/dist/browser.mjs';

    const web5Result = await Web5.connect()

    let did = web5Result.did
    let web5 = web5Result.web5

    console.log('did', did)

    const { records } = await web5.dwn.records.query({
    // from: did,
    message: {
      filter: {
        schema: 'https://schema.org/Playlist',
        dataFormat: 'application/json',
      },
    },
  });

  console.log('records', records)

</script>

</body>
</html>

```

It turns out that we get this error when you pass `from: did` to the query:

![Screenshot 2023-08-25 at 6 26 09 PM](https://github.com/TBD54566975/web5-js/assets/1852675/e208caf9-8ecf-47ff-b464-78bd9922dbc1)

This same record query works if you exclude the `from: did` line.

**Comment by frankhinek** [comment]
Turns out this isn't an issue with `@web5/api` but simply the result of attempting to use the `0.2.1` release of `dwn-sdk-js` in Web5 JS with the hosted `dwn-server` instances that are still running an older version.

When testing with a DWN node that is running `0.2.1` it works as expected:

```javascript
    import { Web5 } from 'https://unpkg.com/@web5/api@0.8.0-alpha-20230823-44789a4/dist/browser.mjs';

    const { web5, did } = await Web5.connect({
      techPreview: {
        dwnEndpoints: ['http://localhost:3000']
      }
    })

    console.log(did)

    const { records } = await web5.dwn.records.query({
      from: did,
      message: {
        filter: {
          schema: 'https://schema.org/Playlist',
          dataFormat: 'application/json',
        },
      },
    });

    console.log(records)
```

The hosted `dwn-server`nodes can't be updated until Web5 JS 0.8 is out but its already past 7pm here on east coast so not going to try to do an update now when there aren't people around to support.
