### ISSUE TITLE
Function name, did.register, is confusing

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#27]
Registering a DID has a well known meaning. 

In the context of web5-js, `web5.did.register` has a different meaning - it's associating a DID with a DWN.

This will lead to a confusing developer experience. Please change the name of this function to a term that's not overloaded

**Comment by frankhinek** [comment]
Appreciate the feedback and for highlighting the potential for confusion.

The name originally stemmed from the concept of having a local registry of cached DIDs that you already had the DID data for (short & long form ID, DID document, private keys, etc.).

More like add to local registry or cache... as opposed to registering a DID with a system that facilitates creation/verification/updating/deactivation of DIDs and DID Documents.  I can see where this might be confusing.

The intent behind this function (currently called `web5.did.register()`) is to register a local DWN/datastore associated with the DID in application state to indicate that the target DID's DWN can be access locally / in-memory... thereby bypassing the need to resolve the DID document and connect to a remote service endpoint.

We can give it more thought but what about changing the function to associate it with the DWN methods rather than DID:

`web5.dwn.register()`

Or something like:

`web5.dwn.registerLocal()`

**Comment by angiejones** [comment]
Putting the method on `dwn` is a good idea

**Comment by mistermoe** [comment]
first question that comes to mind is "wait.. register wut? a dwn?" but better than `web5.did.register`

**Comment by angiejones** [comment]
@csuwildcat is saying DWN handles more so maybe `register` should be at the top level (`web5.register`)

**Comment by mistermoe** [comment]
`web5.consign` lol

**Comment by mistermoe** [comment]
what about `web5.grant`?

<img width="872" alt="image" src="https://user-images.githubusercontent.com/4887440/230496901-90861922-4491-41be-adf0-2b2dafbc900f.png">

**Comment by angiejones** [comment]
> what about `web5.grant`?
> 
> <img alt="image" width="872" src="https://user-images.githubusercontent.com/4887440/230496901-90861922-4491-41be-adf0-2b2dafbc900f.png">

i like `grant`!

**Comment by frankhinek** [comment]
We should probably stay way from using the word _"grant"_ in this context as it is going to get confused with granting of permissions.  The effect of the action also is not related to the "granting" of anything.

_**NOTE:**_ The side-effect of including keys is only an interim approach until a proper "key store" concept is introduced, so I wouldn't focus on that aspect as the primary reason the method `Web5.did.register()` exists.  See below for explanation.

What `web5.did.register()` presently does is:
- record an entry to the `Web5()` instance's DID cache with the following information:
    - `did {string}`: DID that is the tenant/controller of the specified DWN endpoint.
    - `endpoint {string}`: URL where the DWN endpoint can be reached for any actions.  Examples:
        - `app://dwn` for an in-memory DWN (think an in-browser DWN or DWN embedded in an desktop agent app)
        - `http://localhost:55500/dwn` for a local agent app, like `desktop-agent`
        - `https://dwn.tbd.website` for a cloud-hosted DWN
    - `connected {boolean}`: Does the DWA presently have an authorized connection to the endpoint?
    - `keys`: Should be a `{boolean}` that indicates whether the running App that contains this recorded `did/endpoint/connected/keys` information has the public/private keys to sign on behalf of this DID.
        - In the case of an in-browser app, the answer may be yes that it does have keys.
        - In the case of a desktop agent or cloud agent, the answer is likely that it wouldn't have the keys on the browser but would running in the agent app.
        - In the case of using a TPM or SecureElement, none of the running apps would have the private key material.
        - Currently `keys` is an `object` (JSON) containing the key pair for the tenant/controller did, which is used to sign/verify message.  As mentioned earlier, this is a temporary state that will be eliminated when a "key store" construct is introduced to Web5 JS.  At that point, `keys` will become a `boolean`.
- This value is stored in memory because it can change with each invocation of the decentralized web app.  Although it is stored in memory, application developers are expected to provide automatic "registration"/"caching" of any DIDs that the app knows are addressable via a specific endpoint. For example, in the case of a remote endpoint (desktop agent, cloud, etc.), the agent may have multiple DIDs that a single human controls (think social, personal, work accounts) so the user has to select one.  We have this implemented with automatic "registration" in the `desktop-agent` repo today.
- Whenever a call to `web5.dwn.records.write()` or `web5.dwn.protocols.configure()` is made, a `target` and `author` DID is included in the method call indicating which DID the message should be sent to for processing and which DID should sign (could be `alice` signing and writing to `alice`'s DWN or could be `alice` signing and writing to `bob`'s DWN).  If the `target` DID is a DID with a known addressable endpoint (e.g., `app://dwn` for in-memory or `http://localhost:55500/dwn` for a connected desktop agent), when Web5 JS resolves the DID, we DO NOT want it to try and send the message to the remote endpoint specified in the DID document.  This is why `web5.did.register()` is called -- it caches a local entry telling the app -- "hey, don't try to yeet this message to a remote endpoint...  I've got the DWN right here and I've already got keys (or don't) to sign."  When keys are not available to sign but `connected` is `true` for the `author` DID, that means that there's an agent available that this app can send the DWeb Message to so that it can be signed and transported to the targeted DID's endpoint (whether its your own in app memory / localhost or one that can be reached remotely via HTTP/S).

That was a lot but hopefully that context helps.  Happy to walk through an draw it out on a call.

The last bullet point above is **_WHY_** the method was put under `web5.did.register()`... because it impacts what data is returned from DID resolution during the processing of a DWN action (records write/query, protocols configure/query, etc.).

Effectively `web5.did.register()` is annotating some additional information about a specific DID to inform Web5 JS's other functions that when they try to interact with this specific DID, and particularly this DID's DWN, there is more information about how to contact their DWN (the `endpoint` property), whether there is currently a connection to that endpoint (the `connected` property), and whether keys are available to sign (the `keys` property).

Perhaps a more appropriate method call would be: `web5.did.annotate()` ?

**Comment by angiejones** [comment]
Yes, let's do a call. I know there's a whole backstory but it remains that on sight, it's a confusing name because of what it means to "register a DID" outside of web5 js

**Comment by dcrousso** [comment]
how about `web5.dwn.allowDID` or `web5.dwn.associateDID`?

**Comment by angiejones** [comment]
this is done now, right, @frankhinek?
