### ISSUE TITLE
Refactor Key Management in `@web5/crypto`, `@web5/dids`, and `@web5/credentials`

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-js#271]
## Design Guidelines
- The key manager interface must be passed as an argument to all public API methods that require key material. e.g.
    - DID Creation
    - Data Signing
- MVP should include an in-memory Key Manager implementation.
- Consumers of our SDKs should be able to provide their own KeyManager implementations if desired.

## Feature Proposal Tasks:
- [x] Propose API surface design prior to implementation. This can be done by creating a draft PR for a respective feature and providing prototypal code or proposing the design in the comments
- [x] Approval Required from a minimum of 2 people

## Implementation Tasks:
- [x] Produce/update API reference documentation for any/all methods added to the public API surface. documenting private API methods is optional
- [x] Produce/update relevant example usage
- [x] Test coverage must be provided for all public API methods.
- [ ] Tests that consume shared test vectors must all be passing

**Comment by frankhinek** [comment]
# Proposal

## General Design Choices

- Use JSON web key (JWK) as the key format.
    - Conversion utilities provided to convert between JWK and (1) Web Crypto API's `CryptoKey` and (2) raw `Uint8Array` keys.
- Use IANA [JSON Object Signing and Encryption](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms) (JOSE) naming conventions for algorithm, curves, etc. whenever they exist.  JOSE _style_ names used when a standard name is draft/unpublished.
- All I/O that interacts with private or secret keys is done via reference using a `KeyIdentifier` type, which is a `string` value.  Concrete implementations can use any string as the key identifier (e.g. JWK thumbprint, UUID generated by hosted KMS, etc.).
- Provide a base `crypto` interface definition that concrete implementations conform to.
- Any implementation of the `crypto` interface can be passed as an argument to all public API methods that involve key material (e.g., DID creation, VC signing, general data signing/verification, etc.).

## Base Interface

Define a `CryptoApi` interface that all concrete implementations implement/extend:

```typescript
export interface CryptoApi {

  // Key Generation Operations
  generateKey(options: Web5Crypto.GenerateKeyOptions): Promise<Web5Crypto.KeyIdentifier>;

  // Key Derivation Operations
  deriveBits(options: Web5Crypto.DeriveBitsOptions): Promise<Uint8Array>;
  deriveKey(options: Web5Crypto.DeriveKeyOptions): Promise<Web5Crypto.KeyIdentifier>;

  // Key Wrapping Operations
  wrapKey(options: Web5Crypto.WrapKeyOptions): Promise<Uint8Array>;
  unwrapKey(options: Web5Crypto.UnwrapKeyOptions): Promise<JsonWebKey>;

  // Signature Operations
  sign(options: Web5Crypto.SignOptions): Promise<Uint8Array>;
  verify(options: Web5Crypto.VerifyOptions): Promise<boolean>;

  // Hashing Operations
  digest(options: Web5Crypto.DigestOptions): Promise<Uint8Array>;

  // Cipher Operations
  encrypt(options: Web5Crypto.EncryptOptions): Promise<Uint8Array>;
  decrypt(options: Web5Crypto.DecryptOptions): Promise<Uint8Array>;

  // Import/Export Operations
  importKey(options: Web5Crypto.ImportKeyOptions): Promise<Web5Crypto.KeyIdentifier>;
  exportKey(options: Web5Crypto.ExportKeyOptions): Promise<JsonWebKey>;
}
```

## Concrete Implementations

At a minimum, develop and publish two implementations of the `CryptoApi` interface:
- `InMemoryCrypto`:
    - isomorphic implementation (Node.js, web browser, and React Native)
    - prefers the Web Crypto API cryptographic algorithm implementations but substitutes `@noble` or `node:crypto` libs if Web Crypto lacks the required functionality
    - uses an in-memory key store (`Map`)

- `AwsKmsCrypto`: 
    - implementation for back-end development in a Node.js runtime environment
    - limited to the algorithms made available by existing AWS services (initially only [AWS KMS](https://aws.amazon.com/kms/)).
    - all private / secret key material is secured by AWS infrastructure

Consumers of our SDKs can develop their own `CryptoApi` implementations, if desired.  Concrete examples include an implementation for [Google Cloud KMS](https://cloud.google.com/kms/docs), one that persists un-extractable keys in a web browser, or one that offers both in-memory and local key stores depending on whether keys are ephemeral or long-lived.

## Usage Examples

### Key Generation

In-memory:

```typescript
import { InMemoryCrypto } from `@web5/crypto`;

const crypto = new InMemoryCrypto();

const dataEncKeyId = crypto.generateKey({ algorithm: { name: 'A256CTR' }});
console.log(dataEncKeyId) // vDNSXebfrWOE2fzXhJXbRH28tZhuv2FEd9XYow-SpRA
```

AWS KMS:
```typescript
import { AwsKmsCrypto } from `@web5/crypto`;
import { KMSClient } from '@aws-sdk/client-kms';

const kmsClient = new KMSClient({ region: 'us-east1' })
const crypto = new AwsKmsCrypto({ kmsClient });

const dataEncKeyId = crypto.generateKey({ algorithm: { name: 'A256CTR' }});
console.log(dataEncKeyId) // vDNSXebfrWOE2fzXhJXbRH28tZhuv2FEd9XYow-SpRA
```

**Comment by andresuribe87** [comment]
Overall awesome stuff!

Major pieces of feedback/questions:

First, related to 

> Encode raw Uint8Array keys to JWK and decode JWKs to raw Uint8Array keys

What's the motivation for supporting raw keys vs only using JWKs? 

Related to encryption. I think it's important to make key rotation first class. Cloud managers typically provide some form of automatically doing this, but it really depends on the use case. How do you envision key rotation being facilitated by the `CryptoAPI`?

Related to naming, I'm curious why `CryptoAPI`? Did you consider smaller and more focused interfaces?

Lastly, should there be special provisions in order to handle large streams of data (or large files) that need to be signed or encrypted?

**Comment by tomdaffurn** [comment]
Does `digest` do just hashing, or HMAC? Will there be `AlgorithmIdentifier`s for hashing functions? Those don't need keys, so it stands out amongst the other key using operations

**Comment by tomdaffurn** [comment]
`web5-kt` had separate `Crypto`, `KeyManager`, and algorithm classes (e.g. Secp256k1). Seems like `CryptoApi` combines all 3 into one? I like the simplicity of it, but I think there'll be a lot of duplicate code in CryptoApi implementations. Will there be any effort to extract JWK/JOSE, algorithms, or validation to common code?

**Comment by tomdaffurn** [comment]
Having one `AlgorithmIdentifier` type to cover all the different and incompatible algs feels like we're dooming implementers to have validation at the top of every function. At least KDF could be separate from the encrypt/sign algs

**Comment by frankhinek** [comment]
Great questions and feedback @andresuribe87 and @tomdaffurn.

> First, related to
> 
> > Encode raw Uint8Array keys to JWK and decode JWKs to raw Uint8Array keys
> 
> What's the motivation for supporting raw keys vs only using JWKs?

The proposal is to _only_ use the JWK key format in the `CryptoApi` methods.  The suggested "conversion utilities" would make it easy to convert other key formats (e.g., `CryptoKey`, `Uint8Array`, etc.) to/from JWK.  These will likely be needed internally when the underlying KMS or cryptographic algorithm implementations use another format.  For example, an implementation that uses AWS KMS will have to convert ASN.1 DER keys to JWK, like `web5-kt` does in [AwsKeyManager](https://github.com/TBD54566975/web5-kt/blob/fe761a716876c5e87ddde52f35866f8f2e0b69fc/crypto/src/main/kotlin/web5/sdk/crypto/AwsKeyManager.kt#L188-L191).  Another example would be an in-memory or local key store implementation that uses the Web Crypto API for signing, verification, encryption, etc. will have to convert `CryptoKey` to JWK.

> Related to encryption. I think it's important to make key rotation first class. Cloud managers typically provide some form of automatically doing this, but it really depends on the use case. How do you envision key rotation being facilitated by the `CryptoAPI`?

Good question and a topic that deserves more consideration.  How do we balance the simplicity and consistency of an API that provides a set of common crypto operations with more fine-grained configuration and advanced functionality that is only available in some scenarios (e.g., HSM backed)?  What should be considered a "common" operation?  Will consumers of our SDKs use them to manage key rotation or will they implement these policies directly in the underlying KMS?

I used the [Web Crypto API](https://w3c.github.io/webcrypto/) as inspiration, but it obviously doesn't account for features like key rotation.  Additionally, if something like JWK thumbprint is used as a key identifier, how would that work post-key rotation?  We should consider this and other questions to arrive at a consensus.

> Related to naming, I'm curious why `CryptoAPI`? Did you consider smaller and more focused interfaces?

This was partly inspired by the [Web Crypto API](https://w3c.github.io/webcrypto/), but yes other options were considered and I think both @mistermoe and I have prototyped half a dozen versions over the past few months.  In general, the approach was to provide a single API that exposed a common set of cryptographic algorithms including digital signature, cipher, hashing, and key derivation.

A few mentions of other options considered:
- Multiple implementations that are operation specific (`KeyGenerator`, `Signer`, `Cipher`, `Hasher`, etc.) which would be used depending on the need.  For example, a use case that involves JWS might only need the `Signer` for creating and then later verifying a signature whereas JWE might need both a `Signer` and `Cipher`.  Does this improve the developer experience or is easier/intuitive to use a single API to access all of the common crypto operations?
- A single API that implements `KeyGenerator`, `Signer`, `Cipher`, `Hasher`, etc. interfaces such that the API could be used in a unified way or a developer could pull in one of the smaller modules for a specific need.  This would be straightforward to implement in TypeScript but not sure if its possible in Kotlin.
- Use a dot-delimited approach (`crypto.aes.encrypt()`, `crypto.secp256k1.sign()`, `crypto.hmac.sign()`).  You still end up having to pass properties to these methods (curves, length, initialization vector, nonce, salt, etc.), so it isn't clear that this buys you much when IDE intellisense .
 
> Lastly, should there be special provisions in order to handle large streams of data (or large files) that need to be signed or encrypted?

That's an insightful question and one I've been thinking about a lot lately.  The current Web Crypto API supports only one-shot encryption and hashing.  Good read on the subject [here](https://github.com/wintercg/proposal-webcrypto-streams/blob/main/explainer.md) and [here](https://github.com/w3c/webcrypto/issues/73).  A draft community report still under consideration by W3C and browser vendors [here](https://webcrypto-streams.proposal.wintercg.org/).

**Comment by andresuribe87** [comment]
> The suggested "conversion utilities" would make it easy to convert other key formats (e.g., CryptoKey, Uint8Array, etc.) to/from JWK.

Is this something that needs to be exposed as part of the public API? It seems like it's a lower-level implementation detail. In general, I'm a big fan of making public APIs as slim as possible. Smaller public APIs means a smaller surface that needs to be maintained, implemented, and less choice for developers (which translates into less time learning how to use the API). Going from private -> public is much easier than going from public -> private, in case it's something that we really want to expose to the public.

> A single API that implements KeyGenerator, Signer, Cipher, Hasher, etc. interfaces such that the API could be used in a unified way or a developer could pull in one of the smaller modules for a specific need. This would be straightforward to implement in TypeScript but not sure if its possible in Kotlin.

Just noting that my strong preference is to have smaller interfaces like the ones mentioned above. It's possible in most languages that I'm familiar with, including Kotlin, golang and C++. I would also slims down the dependencies that are needed, as devs can pull in only what they need, instead of the whole bundled API. Another benefit is that this conversation can be separated into smaller pieces. For instance, I think we should include encryption until we have a rock solid story of how we're going to support key-rotation (I believe it's crucial that we make sure our design promotes the correct way of doing encryption, which include key-rotation).

**Comment by andresuribe87** [comment]
@frankhinek a couple of additional use cases that I think are important to address.

There is often times where applications need to know whether the private key associated with a public key is available in the instance that implements `CryptoAPI`. For such cases, it would be important to add a method that can address that. One possible solution is to include `containsKey(keyAlias)` as part of the API. This assumes that users have a way of going from `public key` -> `key alias`. So you would need a way to either: 

1. tell `CryptoAPI` which `keyAlias` to use when generating or 
2. have another method in `CryptoAPI` that does `public key` -> `key alias`. 

(2) is what we've implemented in kotlin as shown in https://github.com/TBD54566975/web5-kt/blob/bbef724240451e143e5ba72d829d25c371e440dd/crypto/src/main/kotlin/web5/sdk/crypto/KeyManager.kt#L64

But I actually think we should implement (1). Let me elaborate why below. 

A second, more advanced, use case that's specific to DidIon (and possibly DidWeb). When a user boots up an application for the n-th time, they will likely want to know whether their instance of `CryptoApi` contains all the keys necessary to sign and manage a given did. Let's focus on ION for a second. This means that the application will need to know whether the _latest_ recovery and _latest_ update keys are present. The problem here arises when I do updates. An update to the DID document changes the update key. But, anchoring the update might fail. This introduces race conditions that aren't fun to deal with. From the perspective of a user of the `CryptoAPI`, I believe that this can be fixed if we can pass in arbitrary keyAliases to use (option (1) above), and additionally having a method to **rename** a keyAlias atomically (or have the ability to have multiple aliases for a single key).

 An alternative is to expose transaction functionality with commits and rollbacks, but that sounds very nasty.

**Comment by mistermoe** [comment]
@frankhinek many props for always taking the time to thoroughly explain your proposals and the rationale behind decsions. 

Re:

<img width="1043" alt="image" src="https://github.com/TBD54566975/web5-js/assets/4887440/9bdf7d31-3f92-48e5-97bb-1294aab7d5bd">

ah ok so, if `AwsKmsCrypto` wanted its verify to work the same way as `InMemoryCrypto.verify` works, since verifying doesn't necessitate calls to a KMS, i suppose we could just create an instance of `InMemoryCrypto` _inside_ `AwsKmsCrypto` and call that instance's `verify` function?

**Comment by frankhinek** [comment]
> ah ok so, if AwsKmsCrypto wanted its verify to work the same way as InMemoryCrypto.verify works, since verifying doesn't necessitate calls to a KMS, i suppose we could just create an instance of InMemoryCrypto inside AwsKmsCrypto and call that instance's verify function?

Yes, that's certainly an approach that could be taken.  Ideally implementers have enough of the basic structure and reference implementations in place that they can extend or modify to meet specific use case requirements.

**Comment by decentralgabe** [comment]
A few thoughts:

- byte encoding is not specific enough. for ecdsa keys there are compressed/uncompressed serialization formats, I know RSA has a few different types too. we should provide encoding format recommendations for each key type (or a default practice)
- verification needs to add `audience` as an optional field to make use of the `aud` claim JWTs have
