### ISSUE TITLE
Remove canonical id property from DID objects

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#394]
In both DidKey and DidDht objects, canonicalId property is undefined. This was specific to DidIon. If it's not relevant to DidKey and DidDht, we should remove it

**Comment by frankhinek** [comment]
It turns out that `canonicalId` is critical to DID ION because of the way publishing/anchoring works.  Until we completely remove ION support, we can't just get rid of it.

It's also part of the DID Core spec:
- [`canonicalId`](https://www.w3.org/TR/did-core/#dfn-canonicalid)
- [`equivalentId`](https://www.w3.org/TR/did-core/#dfn-equivalentid)

That being said, the `@web5/dids` refactor we've been talking about for a few weeks was finally merged today so the `Did` object returned is now rather different than it was.

**Comment by frankhinek** [comment]
new `@web5/dids` published as v0.3.0
