### ISSUE TITLE
Local storage keys - More unique?

### ISSUE THREAD

**Issue by sondreb** [TBD54566975/web5-js#4]
The `connect.js` attempts to read key value "keys", that might be fine when the code always runs on a dedicated site, but it's fairly generic and easy to get conflict (especially for developers running on localhost).

Perhaps have a prefix for the whole library that namespaces all the local storage keys?

**Comment by frankhinek** [comment]
Hey @sondreb -- thanks for highlighting this potential issue.

For anyone reading later, local storage keys are scoped to the specific `protocol://host:port`, so less likely to hit conflicts for a publicly accessible deployment or when using with a desktop Web5 agent, but point taken on the potential issue since devs frequently re-use `localhost:3000`, `localhost:8080`, etc.

**Comment by frankhinek** [comment]
Fixed by #13
