### ISSUE TITLE
Make sync configurable

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-js#95]
Sync should be configurable and this feature was requested by multiple community members (example below).

<img width="739" alt="Screenshot 2023-05-22 at 1 19 10 PM" src="https://github.com/TBD54566975/web5-js/assets/134693/10c9cef9-cd3f-489b-9c59-2228f8d51634">

**Comment by mistermoe** [comment]
initial semi-delirious thoughts:

```typescript
const { web5, did } = await Web5.connect({
  techPreview: {
    sync: '5m' | true | false
  }
});
```

* value provided for `sync` can be a `boolean` or a `string`. 
* if string, value is parsed by https://www.npmjs.com/package/ms. 
* if `false`, toggles sync off entirely
* if `true`, toggles sync on with default interval of 1m (totally down for default to be longer)
* defaults to `true`
* the reason i put the option in `techPreview` is because i think configuring sync's interval is actually an agent configuration that wouldn't be controlled by `web5`. imagine alice using multiple web5 apps that are all constantly clobbering s single sync interval for some remote agent
* def lmk if allowing for boolean + hipster string time format feels too "cute".

**Comment by mistermoe** [comment]
another relevant discord discussion starts [here](https://discord.com/channels/937858703112155166/1068273971432280196/1114237954731278388)
